services:
  database:
    image: mongo
    container_name: database
    ports:
      - "27017:27017"
    volumes:
      - ./database:/data/db
    networks:
      - chatbot
      
  mongo_express:
    image: mongo-express
    container_name: mongo_express
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_URL=mongodb://database:27017
      - ME_CONFIG_BASICAUTH_PASSWORD=password
      - ME_CONFIG_BASICAUTH_USERNAME=ahmed
    networks:
      - chatbot

networks:
  chatbot:

volumes:
  database:
